name: Terraform

on:
  push:
    branches:
      - 'main'

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.access_key }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.secret_key }}
      AWS_REGION: eu-west-1
      TF_VAR_aws_region: eu-west-1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan -input=false -no-color -out=tfplan

      - name: Terraform Apply (solo en main)
        if: github.ref == 'refs/heads/main'
        run: terraform apply -input=false -auto-approve tfplan

